services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KonradMichalik\Typo3HeatmapWidget\:
        resource: '../Classes/*'

    KonradMichalik\Typo3HeatmapWidget\Widgets\Provider\SysLogButtonProvider:
        arguments:
            $title: 'LLL:EXT:typo3_heatmap_widget/Resources/Private/Language/locallang.xlf:widgets.recentUpdates.buttonText'

    contentChangesHeatmap:
        class: 'KonradMichalik\Typo3HeatmapWidget\Widgets\Heatmap'
        arguments:
            $dataProvider: '@KonradMichalik\Typo3HeatmapWidget\Widgets\Provider\ContentChangesDataProvider'
            $options:
                dateRangeMode: 'auto'
        tags:
            -   name: dashboard.widget
                identifier: 'contentChangesHeatmap'
                groupNames: 'systemInfo'
                title: 'LLL:EXT:typo3_heatmap_widget/Resources/Private/Language/locallang.xlf:widgets.contentChanges.title'
                description: 'LLL:EXT:typo3_heatmap_widget/Resources/Private/Language/locallang.xlf:widgets.contentChanges.description'
                iconIdentifier: 'heatmap-widget'
                height: 'medium'
                width: 'medium'

    contentChangesHeatmapMonth:
      class: 'KonradMichalik\Typo3HeatmapWidget\Widgets\Heatmap'
      arguments:
        $dataProvider: '@KonradMichalik\Typo3HeatmapWidget\Widgets\Provider\ContentChangesDataProvider'
        $options:
          dateRangeMode: 'auto'
      tags:
        -   name: dashboard.widget
            identifier: 'contentChangesHeatmapSmall'
            groupNames: 'systemInfo'
            title: 'LLL:EXT:typo3_heatmap_widget/Resources/Private/Language/locallang.xlf:widgets.contentChangesSmall.title'
            description: 'LLL:EXT:typo3_heatmap_widget/Resources/Private/Language/locallang.xlf:widgets.contentChangesSmall.description'
            iconIdentifier: 'heatmap-widget'
            height: 'medium'
            width: 'small'

    errorHeatmap:
        class: 'KonradMichalik\Typo3HeatmapWidget\Widgets\Heatmap'
        arguments:
            $dataProvider: '@KonradMichalik\Typo3HeatmapWidget\Widgets\Provider\ErrorDataProvider'
            $options:
                color: '194,24,7'
                dateRangeMode: 'auto'
        tags:
            -   name: dashboard.widget
                identifier: 'errorHeatmap'
                groupNames: 'systemInfo'
                title: 'LLL:EXT:typo3_heatmap_widget/Resources/Private/Language/locallang.xlf:widgets.error.title'
                description: 'LLL:EXT:typo3_heatmap_widget/Resources/Private/Language/locallang.xlf:widgets.error.description'
                iconIdentifier: 'heatmap-widget-error'
                height: 'medium'
                width: 'medium'
