services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KonradMichalik\Typo3Heatmap\:
        resource: '../Classes/*'

    KonradMichalik\Typo3Heatmap\Widgets\Provider\SysLogButtonProvider:
        arguments:
            $title: 'LLL:EXT:typo3_heatmap/Resources/Private/Language/locallang.xlf:widgets.recentUpdates.buttonText'

    contentChangesHeatmap:
        class: 'KonradMichalik\Typo3Heatmap\Widgets\Heatmap'
        arguments:
            $dataProvider: '@KonradMichalik\Typo3Heatmap\Widgets\Provider\ContentChangesHistoryDataProvider'
            $options:
                dateRangeMode: 'auto'
                type: 'content'
        tags:
            -   name: dashboard.widget
                identifier: 'contentChangesHeatmap'
                groupNames: 'systemInfo'
                title: 'LLL:EXT:typo3_heatmap/Resources/Private/Language/locallang.xlf:widgets.contentChanges.title'
                description: 'LLL:EXT:typo3_heatmap/Resources/Private/Language/locallang.xlf:widgets.contentChanges.description'
                iconIdentifier: 'heatmap-widget'
                height: 'medium'
                width: 'medium'

    errorHeatmap:
        class: 'KonradMichalik\Typo3Heatmap\Widgets\Heatmap'
        arguments:
            $dataProvider: '@KonradMichalik\Typo3Heatmap\Widgets\Provider\ErrorDataProvider'
            $options:
                color: '194,24,7'
                dateRangeMode: 'auto'
                tooltipItemSingular: 'LLL:EXT:typo3_heatmap/Resources/Private/Language/locallang.xlf:tooltip.error.singular'
                tooltipItemPlural: 'LLL:EXT:typo3_heatmap/Resources/Private/Language/locallang.xlf:tooltip.error.plural'
                type: 'error'
        tags:
            -   name: dashboard.widget
                identifier: 'errorHeatmap'
                groupNames: 'systemInfo'
                title: 'LLL:EXT:typo3_heatmap/Resources/Private/Language/locallang.xlf:widgets.error.title'
                description: 'LLL:EXT:typo3_heatmap/Resources/Private/Language/locallang.xlf:widgets.error.description'
                iconIdentifier: 'heatmap-widget-error'
                height: 'medium'
                width: 'medium'

    loginHeatmap:
        class: 'KonradMichalik\Typo3Heatmap\Widgets\Heatmap'
        arguments:
            $dataProvider: '@KonradMichalik\Typo3Heatmap\Widgets\Provider\LoginDataProvider'
            $options:
                color: '120,144,156'
                dateRangeMode: 'auto'
                tooltipItemSingular: 'LLL:EXT:typo3_heatmap/Resources/Private/Language/locallang.xlf:tooltip.login.singular'
                tooltipItemPlural: 'LLL:EXT:typo3_heatmap/Resources/Private/Language/locallang.xlf:tooltip.login.plural'
                type: 'login'
        tags:
            -   name: dashboard.widget
                identifier: 'loginHeatmap'
                groupNames: 'systemInfo'
                title: 'LLL:EXT:typo3_heatmap/Resources/Private/Language/locallang.xlf:widgets.login.title'
                description: 'LLL:EXT:typo3_heatmap/Resources/Private/Language/locallang.xlf:widgets.login.description'
                iconIdentifier: 'heatmap-widget-login'
                height: 'medium'
                width: 'medium'
