services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kmi\Typo3HeatmapWidget\:
        resource: '../Classes/*'

    Kmi\Typo3HeatmapWidget\Widgets\Provider\SysLogButtonProvider:
        arguments:
            $title: 'LLL:EXT:typo3_heatmap_widget/Resources/Private/Language/locallang.xlf:widgets.recentUpdates.buttonText'

    contentChangesHeatmap:
        class: 'Kmi\Typo3HeatmapWidget\Widgets\Heatmap'
        arguments:
            $dataProvider: '@Kmi\Typo3HeatmapWidget\Widgets\Provider\ContentChangesDataProvider'
        tags:
            -   name: dashboard.widget
                identifier: 'contentChangesHeatmap'
                groupNames: 'systemInfo'
                title: 'LLL:EXT:typo3_heatmap_widget/Resources/Private/Language/locallang.xlf:widgets.contentChanges.title'
                description: 'LLL:EXT:typo3_heatmap_widget/Resources/Private/Language/locallang.xlf:widgets.contentChanges.description'
                iconIdentifier: 'heatmap-widget'
                height: 'medium'
                width: 'medium'


    errorHeatmap:
        class: 'Kmi\Typo3HeatmapWidget\Widgets\Heatmap'
        arguments:
            $dataProvider: '@Kmi\Typo3HeatmapWidget\Widgets\Provider\ErrorDataProvider'
            $options:
                color: '194,24,7'
        tags:
            -   name: dashboard.widget
                identifier: 'errorHeatmap'
                groupNames: 'systemInfo'
                title: 'LLL:EXT:typo3_heatmap_widget/Resources/Private/Language/locallang.xlf:widgets.error.title'
                description: 'LLL:EXT:typo3_heatmap_widget/Resources/Private/Language/locallang.xlf:widgets.error.description'
                iconIdentifier: 'heatmap-widget'
                height: 'medium'
                width: 'medium'